{"name": "test_add[1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n  +1\n  -2", "trace": "x = 1\n\n    @pytest.mark.parametrize('x',[(1),(2),(3)])\n    def test_add(x):\n>       assert x == random.randrange(1,7)\nE       assert 1 == 2\nE         +1\nE         -2\n\ntest_mark_parametrize.py:11: AssertionError"}, "parameters": [{"name": "x", "value": "1"}], "start": 1596104133453, "stop": 1596104133453, "uuid": "7eb535bc-2300-403c-a00b-53db68f757d5", "historyId": "114af3f85b5ea31c30ea957676a6640a", "testCaseId": "0ced0d8e21e7239fdc59fff1b3a3b804", "fullName": "test_mark_parametrize#test_add", "labels": [{"name": "suite", "value": "test_mark_parametrize"}, {"name": "host", "value": "user-PC"}, {"name": "thread", "value": "15028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_mark_parametrize"}]}